import type { Metadata } from "next";
import "../../components/pokeGrid.css";

export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function PokedexLayout({ children }: LayoutProps<"/pokedex">) {
  return <div className="poke-page mx-auto">{children}</div>;
}
