import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function PokedexLayout({ children }: LayoutProps<"/pokedex">) {
  return (
    <div className="mx-auto mt-8 flex h-[calc(100vh-2rem)] w-full max-w-7xl flex-col">
      {children}
    </div>
  );
}
