import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }: LayoutProps<"/about">) {
  return <>{children}</>;
}
