import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Ben's Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="navBar">
          <Link href="/">
            <div>Home</div>
          </Link>
          <ul className="navBarLinks">
            <li>
              <Link href="/pokedex">Pokedex Demo</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
