import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navBar";
import { ThemeProvider } from "../components/themeProvider";

export const metadata: Metadata = {
  title: "Ben Chamberlain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar label="nav" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
