import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navBar";

export const metadata: Metadata = {
  title: "Ben Chamberlain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar label="nav" />
        {children}
      </body>
    </html>
  );
}
